# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c87e016c2aac4a14aaa7753823e3b52f8b465164449942261c674550bae8c3d0d1cb3516e86629926dd0877562c7f5c67205175300cf08bb56e3312de9e54cc

test:
  secret_key_base: 0be5317107c49c9ffa608e645acd574407cfbec326d29e5b97440bcfe47f51011816d28fff83f47bc7376bcdb1657adcff34e7e59895384ad0792f5b325f0c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
